title: "AK's Homepage" 
author: Ashok Kumar
# email: "derekkedziora@icloud.com"
description: "A website for learning and sharing knowledge"
github: akvsak
markdown: kramdown
kramdown:
  math_engine: katex
parse_block_html: false
url: https://akvsak.github.io/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed

feed: 
  categories:
    - now