title: "Ashok Kumar's Homepage" 
author: Ashok Kumar
# email: "derekkedziora@icloud.com"
description: "A Jekyll demo site with a dark mode switch and random post feature"
github: akvsak
markdown: kramdown
parse_block_html: false
url: https://akvsak.github.io/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed

feed: 
  categories:
    - now